### ISSUE TITLE
doesnt work on osx

### ISSUE THREAD

**Issue by jackmahoney** [konsumer/tindercred#3]
doesnt seem to work at the moment

**Comment by konsumer** [comment]
Hmm. yeh, if I run it from master I get "not logged in" error in the facebook popup. I will investigate.

**Comment by konsumer** [comment]
Ok, so it looks like tinder disabled the redirect domain that used to work.

This isn't mac-specific, and affects anything that wants to spoof being tinder for login on the web.  I can't use tokens from any other app (must be 464891386855067, the tinder app.) I think watching network traffic to figure out what tinder app sets `redirect_uri` to is the next step. We need ours to match. I am making another issue at the underlying library that does auth.

konsumer/jstinder#1

I don't use tinder anymore, so if anyone wants to wireshark their wifi to get the `redirect_uri`, that'd be rad.
